project_id = "personal-wealth"

[functions.admin-users]
verify_jwt = true

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[auth]
enabled = true
site_url = "http://127.0.0.1:4173"
additional_redirect_urls = ["http://localhost:4173", "http://127.0.0.1:4173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.sessions]
timebox = "168h"
